version: '3.9'
services:
  flask:
    container_name: flask
    build: 
      context: frontend
      dockerfile: Dockerfile.flask
    restart: on-failure
    networks:
    - frontend

  nginx:
    container_name: nginx
    build:
      context: frontend
      dockerfile: Dockerfile.nginx
    restart: on-failure
    networks:
    - frontend
    ports: 
    - 8080:80

networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.17.0.0/24
          gateway: 10.17.0.1
